apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.8.5
    helm: 
      parameters:
        - name: service.type
          value: "NodePort"
      releaseName: grafana
      namespace: monitoramento
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoramento
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  