apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
  namespace: apps
spec:
  project: default
  source:
    repoURL: https://github.com/LucasRius/lrios-app-demo.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
